# Generated by Django 4.2.28 on 2026-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(max_length=500)),
                ('repo_name', models.CharField(max_length=255)),
                ('compliance_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('report_json', models.JSONField()),
                ('scan_status', models.CharField(default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repo_url'], name='scanner_sca_repo_ur_8923ac_idx'), models.Index(fields=['created_at'], name='scanner_sca_created_2e4cbb_idx')],
            },
        ),
    ]
